development:
  adapter: mysql2
  encoding: utf8
  database: google_hackathon_api_development
  pool: 5
  host: localhost
  username: root
  password: SQL_BuddhA024878
production:
  adapter: mysql2
  encoding: utf8
  database: google_hackathon_api_production
  pool: 5
  host: 173.194.244.85
  username: root
  password: SQL_BuddhA024878
